<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE jmxetric-config [
   <!ELEMENT jmxetric-config (sample|ganglia|jvm)*>
   <!ELEMENT sample (mbean)*>
      <!ATTLIST sample delay CDATA #REQUIRED>
      <!ATTLIST sample initialdelay CDATA "0">
   <!ELEMENT mbean (attribute)*>
      <!ATTLIST mbean name CDATA #REQUIRED>
      <!ATTLIST mbean pname CDATA #REQUIRED>
   <!ELEMENT attribute (composite*)>
      <!ATTLIST attribute name CDATA #REQUIRED>
      <!ATTLIST attribute type CDATA "" >
      <!ATTLIST attribute units CDATA "" >
      <!ATTLIST attribute pname CDATA "" >
      <!ATTLIST attribute slope CDATA "both" >
   <!ELEMENT composite EMPTY>
      <!ATTLIST composite name CDATA #REQUIRED>
      <!ATTLIST composite type CDATA "" >
      <!ATTLIST composite units CDATA "" >
      <!ATTLIST composite pname CDATA "" >
      <!ATTLIST composite slope CDATA "both" >
   <!ELEMENT ganglia EMPTY>
      <!ATTLIST ganglia hostname CDATA #REQUIRED>
      <!ATTLIST ganglia port CDATA #REQUIRED>
      <!ATTLIST ganglia mode CDATA #REQUIRED>
      <!ATTLIST ganglia wireformat31x CDATA #REQUIRED>
   <!ELEMENT jvm EMPTY>
      <!ATTLIST jvm process CDATA "">
]>

<jmxetric-config>

    <!--
     ~ ************************************************************************
     ~ <jvm process="ProcessName"/>
     ~   A name that is prefixed to the metric name before publication (so that
     ~   metrics from different JVMs on the same host can be determined).
     ~   If the "process" name is specified in -javaagent arguments, 
     ~   it overrides this specification.
     ~ 
     ~ <sample initialdelay="0" delay="60">
     ~   In seconds. default initialdelay=0. default delay=60.
     ~
     ~ Support types: 
     ~   string|int8|uint8|int16|uint16|int32|uint32|float|double
     ~   for a long type, use double here.
     ~
     ~  The composite within a attribute should implement CompositeData.
     ~ ************************************************************************
     -->

	<jvm process="ProcessName"/>
	
	<sample initialdelay="10" delay="60">
	
		<mbean name="java.lang:type=Memory" pname="Memory">
			<attribute name="HeapMemoryUsage">
				<composite name="init" pname="Heap_init" type="int32" units="bytes"/>
				<composite name="committed" pname="Heap_committed" type="int32" units="bytes"/>
				<composite name="used" pname="Heap_used" type="int32" units="bytes" />
				<composite name="max" pname="Heap_max" type="int32" units="bytes" />
			</attribute>
			<attribute name="NonHeapMemoryUsage" >
				<composite name="init" pname="NonHeap_init" type="int32"  units="bytes" />
				<composite name="committed" pname="NonHeap_committed" type="int32" units="bytes" />
				<composite name="used" pname="NonHeap_used" type="int32" units="bytes" />
				<composite name="max" pname="NonHeap_max" type="int32" units="bytes" />
			</attribute>
		</mbean>
		
		<mbean name="java.lang:type=Threading" pname="Threading" >
			<attribute name="ThreadCount" type="int16" />
			<attribute name="DaemonThreadCount" type="int16" />
		</mbean>
		
		<mbean name="java.lang:type=OperatingSystem" pname="OS" >
			<attribute name="ProcessCpuTime" type="int32" slope="positive"/>
		</mbean>
		
	</sample>
	
	<!--
     ~ ************************************************************************
     ~ Specify the configuration of ganglia gmond. These attributes can also
     ~ be defined in -javaagent arguments in java commandline. e.g: 
     ~ -javaagent:/full/path/to/jmxetric.jar=host=239.2.11.70,port=8649,
     ~ mode=multicast,wireformat31x=true,config=/full/path/to/jmxetric.xml.
     ~ But, if they are specified in -javaagent arguments, following attributes
     ~ will be overrided.
     ~ 
     ~ hostname,port: The multicast address that is used to publish metrics
     ~                to the ganglia gmond.
     ~ mode:          The UDP addressing mode, either multicast or unicast
     ~                (default multicast).
     ~ wireformat31x: True if the ganglia v3.1.x wire format should be used
     ~                (default false).
     ~ ************************************************************************
     -->
	<ganglia hostname="localhost" port="8649" mode="multicast" wireformat31x="true" />
	
</jmxetric-config>

